name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    
    - name: Setup RimWorld References
      run: |
        mkdir -p References
        curl -L -o References/Assembly-CSharp.dll https://github.com/${{ github.repository }}/releases/download/references/Assembly-CSharp.dll
        curl -L -o References/UnityEngine.dll https://github.com/${{ github.repository }}/releases/download/references/UnityEngine.dll
        curl -L -o References/UnityEngine.CoreModule.dll https://github.com/${{ github.repository }}/releases/download/references/UnityEngine.CoreModule.dll
        curl -L -o References/UnityEngine.IMGUIModule.dll https://github.com/${{ github.repository }}/releases/download/references/UnityEngine.IMGUIModule.dll
        curl -L -o References/UnityEngine.TextRenderingModule.dll https://github.com/${{ github.repository }}/releases/download/references/UnityEngine.TextRenderingModule.dll

    - name: Build
      run: |
        dotnet build Source/StockpileSelector/StockpileSelector.csproj -c Release
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: StockpileSelector
        path: Assemblies/StockpileSelector.dll 